spring:
  application:
    name: cloud-stream-binder-producer

  cloud:
    stream:
      kafka:
        binder:
          brokers: 1.15.41.168
          zkNodes: 1.15.41.168

      bindings:
        output:
          destination: stream.message

        my_output:
          destination: mystream.message

        source:
          destination: source.message
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                host: 1.15.41.168